# Generated by Django 4.2.30 on 2026-04-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_add_personal_info_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='professional_summary',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='template_style',
            field=models.CharField(default='classic', max_length=20),
        ),
    ]
