# Generated by Django 4.2.30 on 2026-04-18 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_professional_summary_resume_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='resumes.resume'),
        ),
    ]
